export const VERTICALS = {
  pharmacy: { id:'pharmacy', label:'Pharmacy (distributor)',
    schema:['drug_name','batch_no','expiry','schedule','hsn','mrp'],
    chit_types:['purchase_order','goods_receipt','prescription_fulfilment','return'],
    preset_lenses:{ vocabulary:'formal', navigation:'sidebar' }, contributes:{ catalogue_visibility:'restricted' } },
  marketplace: { id:'marketplace', label:'Marketplace (Amazon-style)',
    schema:['title','brand','price','stock','category','rating'],
    chit_types:['order','quote','return','review'],
    preset_lenses:{ vocabulary:'casual', navigation:'tab-bar', comparison:'on' }, contributes:{ catalogue_visibility:'public' } },
  hospital: { id:'hospital', label:'Hospital (care network)',
    schema:['patient_ref','service','department','tariff','insurer'],
    chit_types:['admission','service_order','claim','discharge'],
    preset_lenses:{ vocabulary:'formal', navigation:'wizard' }, contributes:{ catalogue_visibility:'private' } },
  manufacturer: { id:'manufacturer', label:'Manufacturer (production chain)',
    schema:['sku','bom_ref','work_order','batch','qc_status','uom'],
    chit_types:['work_order','material_issue','goods_receipt','qc_pass'],
    preset_lenses:{ vocabulary:'formal', navigation:'sidebar' }, contributes:{ catalogue_visibility:'restricted' } },
};
