// Build public/demo.html — a standalone, embeddable copy of the Demo Theatre.
//
// Why a generator (not a hand-maintained file): the Theatre (data + player) lives
// once, inside public/app.html. This extracts that block and wraps it in a tiny
// self-contained page, so demo.html can NEVER drift from the app. Re-run after any
// Theatre change:  npm run build:demo   (or: node scripts/build-demo.js)
//
// The output has NO login, NO API, NO dependencies — embed it anywhere:
//   <iframe src="/demo.html" style="width:100%;height:680px;border:0"></iframe>
// or just link to /demo.html (works outside login, e.g. the marketing homepage).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appHtml = path.join(__dirname, "..", "public", "app.html");
const outFile = path.join(__dirname, "..", "public", "demo.html");

const html = fs.readFileSync(appHtml, "utf8");
const start = html.indexOf("const THEATRE = {");
const end = html.indexOf("SESSION + ROUTER");
if (start < 0 || end < 0) {
  console.error("build-demo: could not find the Theatre block in public/app.html");
  process.exit(1);
}
let slice = html.slice(start, end);
slice = slice.slice(0, slice.lastIndexOf("}") + 1); // trim the trailing comment opener

const out = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Chit & Bridge - See both sides</title>
<meta name="description" content="Watch a single order travel between two businesses on Chit & Bridge - one deal, two copies, messages and isolation, narrated step by step.">
<style>html,body{margin:0;height:100%;font-family:-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:#eef1f4}</style>
</head>
<body>
<script>
/* GENERATED by scripts/build-demo.js from public/app.html - do not edit by hand. */
/* Standalone & embeddable: no login, no API, no network calls. */
function esc(v){ return String(v==null?'':v).replace(/[<>"&]/g,function(c){return ({'<':'&lt;','>':'&gt;','"':'&quot;','&':'&amp;'})[c];}); }

${slice}

// The page IS the theatre: open on load; the close button restarts (never blanks).
closeTheatre = function(){ startPlayer(); };
openTheatre();
</script>
</body>
</html>
`;

// Sanity: the generated inline script must parse.
const m = out.match(/<script>([\s\S]*?)<\/script>/);
try { new vm.Script(m[1]); }
catch (e) { console.error("build-demo: generated script failed to parse - " + e.message); process.exit(1); }

fs.writeFileSync(outFile, out, "utf8");
console.log("build-demo: wrote " + path.relative(path.join(__dirname, ".."), outFile) + " (" + Buffer.byteLength(out) + " bytes) - syntax OK");
