export const PENDING_DECISIONS = [
  { id:'PD-001', layer:'jurisdiction', status:'pending',
    title:'Incomparable bound floors (data residency: EU vs India)',
    question:'When two jurisdictions each set a BOUND floor on the same key with no common value, how does the engine resolve?',
    example:{ key:'data_residency', a:{ source:'India', value:'in' }, b:{ source:'EU', value:'eu' } },
    options:['Reject — no common value, un-mintable, cite both authorities','Precedence picks one (install-pinned jurisdiction wins)','Governed override / waiver (attested, time-boxed)','Split by data-class (some fields in-India, some in-EU)'],
    recommended:'Reject + cite both, unless a data-class split or governed waiver is configured', gates:'GOV-01 resolver (gap A1)' },
  { id:'PD-002', layer:'engine', status:'pending', title:'Resolver shape — generalise to all sources',
    question:'Move the production resolver from (constitution, override) to resolve(orderedSources[], override)?',
    options:['Yes — fold all six layers in as sources','No — keep constitution-only for v1'],
    recommended:'Yes — converge with the simulator resolver', gates:'GOV-01 resolver (A2)' },
  { id:'PD-003', layer:'engine', status:'pending', title:'Governed waiver for Class A/B',
    question:'Allow a time-boxed, attested, audited override of a floor?',
    options:['Yes — governed waivers','No — hard-reject only'],
    recommended:'Yes — distinct from silent loosening', gates:'GOV-01 (C1)' },
  { id:'PD-004', layer:'data', status:'pending', title:'Purpose-bind the data union',
    question:"Collect only the union necessary for a chit's purpose (vs all-fields-ever)?",
    options:['Yes — purpose-scoped projection','No — full union'],
    recommended:'Yes — minimisation counter-force (GDPR)', gates:'data model (G1)' },
  { id:'PD-005', layer:'jurisdiction', status:'pending', title:'Default tenancy / minus placement',
    question:'Is multi-tenant (entity-level minus) the default, single-shared-ERP the special case?',
    options:['Multi-tenant default','Single-ERP default'],
    recommended:'Multi-tenant default', gates:'user-preference step' },
];
